services:
  hartzadb:
    image: postgres:16-alpine
    container_name: hartza-db
    restart: always
    environment:
      POSTGRES_USER: hartza
      POSTGRES_PASSWORD: hartza
      POSTGRES_DB: hartza
    ports:
      - "5436:5432"
    volumes:
      - /mnt/ssd-all/hartza/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hartza -d hartza"]
      interval: 5s
      timeout: 5s
      retries: 20

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: hartza-mailhog
    restart: always
    profiles: ["optional"]
    ports:
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 30s
      timeout: 10s
      retries: 3

  hartza-web:
    build:
      context: .          # you're already running compose ON Hurska in the NFS mount — good
      target: dev
      # If Hurska is Pi 3, uncomment:
      # platform: "linux/arm/v7"
    container_name: hartza-web
    working_dir: /app
    env_file: [.env]
    environment:
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "true"
    ports: ["5127:3000"]
    restart: always
    volumes:
      - ./:/app                         # NFS-mounted source
      - node-modules:/app/node_modules  # keep deps internal
      # Optional caches (pick what your framework uses):
      - next-cache:/app/.next
      - vite-cache:/app/node_modules/.vite
      - npm-cache:/root/.npm
    depends_on:
      hartzadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  hartza-cron:
    image: alpine:3.20
    container_name: hartza-cron
    volumes:
      - ./cronjobs:/etc/crontabs/root
    command: crond -f -L /dev/stdout
    restart: always
    environment:
      - CRON_SECRET=${CRON_SECRET}
    depends_on:
      - hartza-web
    healthcheck:
      test: ["CMD", "pgrep", "crond"]
      interval: 60s
      timeout: 5s
      retries: 3

volumes:
  node-modules:
  next-cache:
  vite-cache:
  npm-cache:

